### ISSUE TITLE
Automated Intervention Tracking Form Generation

### ISSUE THREAD

**Issue by shwndea** [code4sac/learning-blocks#45]
- [ ] Using [The Intervention Tracking Form](https://drive.google.com/file/d/1sMRP2t8TVsPhMBR3-d1ByTBdn2L_8w9O/view?usp=sharing) as a template generate a PDF Report of the following information in [Intervention Tracking Form Fields](https://docs.google.com/document/d/17xA3sfqNd6QjA4R2LOnflrsVsiQN3H2E/edit?usp=sharing&ouid=115120292425227650709&rtpof=true&sd=true)

**Comment by marcolo-IT** [comment]
Hello there, I believe this python script will serve as a good starting point for this task. 

After fetching the data points for a particular student and inputting it into the respective table function, it will generate the word document based on a template I created, then convert it into a PDF Report as requested. Although it's not dynamic, current sheet does support up to four tables, and more tables can be added on the template efficiently.

Here's the [.zip folder](https://drive.google.com/drive/folders/1NWIibM2z1f_stwBBckOW7v7CJmXQ1rW_?usp=sharing) containing the python script, the word doc template, and the sample output files.

Just run "doc_to_pdf.py" after changing its file path for the template.docx to see a quick [demonstration](https://drive.google.com/file/d/1Iu-nqc4vaAHVGl3J5lcpyleMekvQ73YF/view?usp=sharing).

**Comment by shwndea** [comment]
This is amazing!!! The next portion of the project is to make the model, schemas, endpoints etc for the class that will house this needed fields for this project.  So the next tasks are:

- [ ] Add this project to the backend
- Models
- Schemas
- D.B.Base
- D.B.init_db
- Endpoints
- api.api_v1.api.pv
- CRUD
- _ _init _ _
- crud_new_table_class
- [ ] Make Visuals to for frontend
- [ ] Make Documentation for this process and how to update it.
- [ ] Link the backend tables to the frontend user interface

**Comment by shwndea** [comment]
I also made some updates to the script Marco provided: it can be seen here:
https://github.com/code4sac/learning-blocks/tree/main/Stand_%20Alone_%20Python_%20Scripts/Interventions_PDF_Report
